name: CI
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build
      run: go build -v .

    - name: Build Docker image
      env:
        DOCKER_PASSWD: ${{ secrets.DOCKER_PASSWD }}
        IMAGE: foryasee/time-service
      run: |
        docker login -u foryasee -p $DOCKER_PASSWD
        docker build -t ${IMAGE} . -f Dockerfile
        docker tag ${IMAGE} ${IMAGE}:latest
        docker push ${IMAGE}
